import { JSDOM } from "jsdom";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const html=fs.readFileSync(path.join(root,"web/antipatterns.html"),"utf8");
const dom=new JSDOM(html,{runScripts:"dangerously",url:"https://host.test/repo/antipatterns.html"});
const share=dom.window.__QUIZ_V1__.performShare;
const assert=(x,m)=>{if(!x)throw new Error(m)};
const events=[];
const ui={success:()=>events.push("success"),manual:v=>events.push(`manual:${v}`)};
let copied=0;
await share({nav:{share:async p=>{assert(p.url.includes("antipatterns.html?quiz="),"native payload URL missing");},clipboard:{writeText:async()=>{copied++}}},url:"https://host.test/repo/antipatterns.html?quiz=setup&qv=1#quiz-section",text:"quiz",ui});
assert(copied===0,"native success must not copy");
let abortNav={clipboard:{writeText:async()=>{copied++}}};
Object.defineProperty(abortNav,"share",{get(){throw new dom.window.DOMException("cancel","AbortError")}});
await share({nav:abortNav,url:"u",text:"t",ui});
assert(copied===0,"sync AbortError property access must be silent/no copy");
await share({nav:{share:()=>Promise.reject(new dom.window.DOMException("cancel","AbortError")),clipboard:{writeText:async()=>{copied++}}},url:"u",text:"t",ui});
assert(copied===0,"async AbortError must be silent/no copy");
await share({nav:{share(){throw new dom.window.DOMException("cancel","AbortError")},clipboard:{writeText:async()=>{copied++}}},url:"u",text:"t",ui});
assert(copied===0,"sync invocation AbortError must be silent/no copy");
await share({nav:{share(){throw new Error("native")},clipboard:{writeText:async()=>{copied++}}},url:"copy-me",text:"t",ui});
assert(copied===1&&events.includes("success"),"sync native error must use clipboard and announce");
const nativeAccess={clipboard:{writeText:async()=>{copied++}}};
Object.defineProperty(nativeAccess,"share",{get(){throw new Error("blocked")}});
await share({nav:nativeAccess,url:"copy-access",text:"t",ui});
await share({nav:{share:()=>Promise.reject(new Error("native")),clipboard:{writeText:async()=>{copied++}}},url:"copy-reject",text:"t",ui});
await share({nav:{clipboard:{writeText:async()=>{copied++}}},url:"copy-no-native",text:"t",ui});
assert(copied===4,"native access/rejection/absence must each fall back to clipboard");
const badClipboard={}; Object.defineProperty(badClipboard,"writeText",{get(){throw new Error("denied")}});
await share({nav:{share:()=>Promise.reject(new Error("native")),clipboard:badClipboard},url:"manual-me",text:"t",ui});
assert(events.includes("manual:manual-me"),"clipboard property/access failure must reveal manual value");
const clipboardAccess={}; Object.defineProperty(clipboardAccess,"clipboard",{get(){throw new Error("denied")}});
await share({nav:clipboardAccess,url:"manual-access",text:"t",ui});
await share({nav:{clipboard:{writeText(){throw new Error("denied")}}},url:"manual-sync",text:"t",ui});
assert(events.includes("manual:manual-access")&&events.includes("manual:manual-sync"),"clipboard object access and sync invocation failures must reveal manual value");
await share({nav:{clipboard:{writeText:()=>Promise.reject(new Error("denied"))}},url:"manual-async",text:"t",ui});
assert(events.includes("manual:manual-async"),"async clipboard rejection must reveal manual value");
console.log("QUIZ_V1_SHARE_PASS native=success abort=property+call+promise fallback=access+call+promise manual=access+call+promise");
